FWA-56 - Allow valid branch names and commit messages only (#17)
FWA-56 - Allow valid branch names and commit messages only

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -1,16 +1,32 @@
 #!/usr/bin/env bash
 LC_ALL=C
 
+# Validate branch name
 local_branch="$(git rev-parse --abbrev-ref HEAD)"
+valid_branch_regex="^(feature|bugfix|task)\/fwa-[0-9]+$"
 
-valid_branch_regex="^(feature|bugfix|task)\/[a-z0-9._-]+$"
+branch_message_error="Invalid branch name. Branch names must adhere to this contract: $valid_branch_regex. Your commit will be rejected. Please rename your branch and try again."
 
-message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again."
-
-if [[ ! $local_branch =~ $valid_branch_regex ]]
-then
-    echo "$message"
+if [[ ! $local_branch =~ $valid_branch_regex ]]; then
+    echo "$branch_message_error"
     exit 1
 fi
 
+# Validate commit messages
+commit_message_regex="^FWA-[0-9]+"
+commit_message_error="Invalid commit message. Commit messages must start with 'FWA-' followed by a number (e.g., 'FWA-123')."
+
+# Fetch the list of commits to be pushed
+commits=$(git log --oneline origin/$(git rev-parse --abbrev-ref HEAD)..HEAD)
+
+while IFS= read -r commit; do
+    commit_message=$(echo "$commit" | cut -d ' ' -f2-)
+    if [[ ! $commit_message =~ $commit_message_regex ]]; then
+        echo "$commit_message_error"
+        echo "Invalid commit: $commit"
+        exit 1
+    fi
+done <<< "$commits"
+
+# If all validations pass
 exit 0
